# Generated by Django 2.2.12 on 2021-12-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='服务时间')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('link', models.CharField(max_length=300, verbose_name='文章链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='记录时间')),
                ('title', models.CharField(max_length=100, verbose_name='日志标题')),
                ('description', models.TextField(verbose_name='内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='项目日期')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(verbose_name='项目描述')),
                ('link', models.CharField(max_length=300, verbose_name='项目链接')),
                ('auther_list', models.CharField(max_length=100, verbose_name='作者列表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='发表时间')),
                ('title', models.CharField(max_length=100, verbose_name='论文标题')),
                ('description', models.TextField(verbose_name='论文描述')),
                ('link', models.CharField(max_length=300, verbose_name='论文链接')),
                ('auther_list', models.CharField(max_length=100, verbose_name='作者列表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100, verbose_name='获奖日期')),
                ('title', models.CharField(max_length=100, verbose_name='奖项title')),
                ('description', models.TextField(verbose_name='获奖描述')),
                ('link', models.CharField(max_length=300, verbose_name='相关链接')),
                ('auther_list', models.CharField(max_length=100, verbose_name='作者列表')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='academy_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(verbose_name='自我介绍')),
                ('intro_num', models.IntegerField(default=0, verbose_name='intro_num')),
                ('paper_num', models.IntegerField(default=0, verbose_name='paper_num')),
                ('project_num', models.IntegerField(default=0, verbose_name='project_num')),
                ('record_num', models.IntegerField(default=0, verbose_name='record_num')),
                ('service_num', models.IntegerField(default=0, verbose_name='service_num')),
                ('award_num', models.IntegerField(default=0, verbose_name='award_num')),
                ('phone_link', models.CharField(default='#', max_length=300, verbose_name='电话号码')),
                ('email_link', models.CharField(default='#', max_length=300, verbose_name='邮箱地址')),
                ('github_link', models.CharField(default='#', max_length=300, verbose_name='github地址')),
                ('zhihu_link', models.CharField(default='#', max_length=300, verbose_name='知乎地址')),
                ('blog_link', models.CharField(default='#', max_length=300, verbose_name='博客地址')),
                ('name', models.CharField(max_length=100, verbose_name='主页名字')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('pic', models.ImageField(default='/static/images/bk.jpg', upload_to='image', verbose_name='上传的图片')),
                ('fans_num', models.IntegerField(default=0, verbose_name='fans_num')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
