# Generated by Django 2.2.12 on 2021-12-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.CharField(blank=True, max_length=128, null=True)),
                ('following', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
