# Generated by Django 2.2.12 on 2021-12-25 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpCoordinate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_str', models.CharField(default=None, max_length=32, unique=True, verbose_name='ip地址')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='市/区')),
                ('x', models.CharField(max_length=16, verbose_name='经度')),
                ('y', models.CharField(max_length=16, verbose_name='维度')),
            ],
            options={
                'verbose_name': 'IP地址经纬度坐标',
                'verbose_name_plural': 'IP地址经纬度坐标',
                'db_table': 't_ip_coordinate',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default=None, max_length=512, verbose_name='访问地址')),
                ('visit_time', models.DateTimeField(auto_now_add=True, max_length=32, verbose_name='访问时间')),
                ('coordinate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='statistic.IpCoordinate')),
            ],
            options={
                'verbose_name': '访客统计',
                'verbose_name_plural': '访客统计',
                'db_table': 't_site_statistic',
            },
        ),
    ]
