# Generated by Django 2.2.12 on 2021-12-25 02:06

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('tag1', models.CharField(max_length=30, verbose_name='标签1')),
                ('tag2', models.CharField(max_length=30, verbose_name='标签2')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数量')),
                ('seen_num', models.IntegerField(default=0, verbose_name='阅读数量')),
                ('ok_num', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否可见')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
