# Generated by Django 2.2.12 on 2021-12-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('blog_num', models.IntegerField(default=0, verbose_name='博客数量')),
                ('mail_address', models.CharField(max_length=20, verbose_name='邮箱地址')),
                ('user_level', models.IntegerField(default=0, verbose_name='用户等级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
